/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pd1_test_plehanovs;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 *
 * @author Maksims Pļehanovs
 */
public class PD1_GUI_Plehanovs extends javax.swing.JFrame {

    private static final String url = "jdbc:derby://localhost:1527/QuizDB";
    private static final String user = "dbuser";
    private static final String password = "dbuser";

    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(url, user, password);
    }

    /**
     * Creates new form PD1_GUI_Plehanovs
     */
    public PD1_GUI_Plehanovs() {
        initComponents();
    }

    public static class Question {

        public int id;
        public String questionText;
        public String[] options = new String[3];

        public Question(int id, String qText, String opt1, String opt2, String opt3) {
            this.id = id;
            this.questionText = qText;
            this.options[0] = opt1;
            this.options[1] = opt2;
            this.options[2] = opt3;
        }
    }

    public Question getQuestionById(int questionId) {
        try (Connection conn = PD1_GUI_Plehanovs.getConnection()) {
            String sql = "SELECT * FROM questions WHERE id = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, questionId);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                return new Question(
                        rs.getInt("id"),
                        rs.getString("question_text"),
                        rs.getString("option1"),
                        rs.getString("option2"),
                        rs.getString("option3")
                );
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistracijasLogs = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RegistrationConfirm = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        TestaSakumsLogs = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TestStart = new javax.swing.JButton();
        RezultatuLogs = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        SlavasSarakstaLogs = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        IzvelesLogs = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        PirmaJautajumaLogs = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();
        OtraJautajumaLogs = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jButton12 = new javax.swing.JButton();
        TresaJautajumaLogs = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jButton13 = new javax.swing.JButton();
        CeturtaJautajumaLogs = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jButton14 = new javax.swing.JButton();
        PiektaJautajumaLogs = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jButton15 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        RegistrationButton = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        RegistracijasLogs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistracijasLogsMouseClicked(evt);
            }
        });
        RegistracijasLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                RegistracijasLogsWindowClosed(evt);
            }
        });

        jLabel3.setText("Vārds:");

        jLabel4.setText("Uzvārds:");

        jLabel5.setText("Lietotājvārds:");

        jLabel6.setText("Parole:");

        jLabel7.setText("Parole(atkārtoti):");

        RegistrationConfirm.setText("Reģistrēties");
        RegistrationConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrationConfirmMouseClicked(evt);
            }
        });
        RegistrationConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegistracijasLogsLayout = new javax.swing.GroupLayout(RegistracijasLogs.getContentPane());
        RegistracijasLogs.getContentPane().setLayout(RegistracijasLogsLayout);
        RegistracijasLogsLayout.setHorizontalGroup(
            RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistracijasLogsLayout.createSequentialGroup()
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistracijasLogsLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RegistracijasLogsLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(RegistrationConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegistracijasLogsLayout.setVerticalGroup(
            RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistracijasLogsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RegistrationConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TestaSakumsLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                TestaSakumsLogsWindowClosed(evt);
            }
        });

        jLabel8.setText("Tests \"Testa nosaukums\"");

        jLabel9.setText("Meģinājuma skaits: ");

        TestStart.setText("Sākt testu");
        TestStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TestStartMouseClicked(evt);
            }
        });
        TestStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TestaSakumsLogsLayout = new javax.swing.GroupLayout(TestaSakumsLogs.getContentPane());
        TestaSakumsLogs.getContentPane().setLayout(TestaSakumsLogsLayout);
        TestaSakumsLogsLayout.setHorizontalGroup(
            TestaSakumsLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestaSakumsLogsLayout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addGroup(TestaSakumsLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TestStart, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(TestaSakumsLogsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TestaSakumsLogsLayout.setVerticalGroup(
            TestaSakumsLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestaSakumsLogsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addGap(34, 34, 34)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(TestStart, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        RezultatuLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                RezultatuLogsWindowClosed(evt);
            }
        });

        jLabel11.setText("Rezultāti");

        jLabel12.setText("Lietotājs:");

        jLabel13.setText("Procenti:");

        jLabel14.setText("Atzīme:");

        jButton6.setText("Iesniegt");

        jButton7.setText("Pildīt vēlreiz");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("Paradīt Slavas sarakstu");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RezultatuLogsLayout = new javax.swing.GroupLayout(RezultatuLogs.getContentPane());
        RezultatuLogs.getContentPane().setLayout(RezultatuLogsLayout);
        RezultatuLogsLayout.setHorizontalGroup(
            RezultatuLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RezultatuLogsLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(RezultatuLogsLayout.createSequentialGroup()
                .addGroup(RezultatuLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RezultatuLogsLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(RezultatuLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(87, 87, 87)
                        .addComponent(jLabel14))
                    .addGroup(RezultatuLogsLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel11))
                    .addGroup(RezultatuLogsLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RezultatuLogsLayout.setVerticalGroup(
            RezultatuLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RezultatuLogsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(31, 31, 31)
                .addComponent(jLabel12)
                .addGap(35, 35, 35)
                .addGroup(RezultatuLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(RezultatuLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        SlavasSarakstaLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                SlavasSarakstaLogsWindowClosed(evt);
            }
        });

        jLabel15.setText("Slavas saraksts");

        jLabel16.setText("Rezultāti");

        jButton9.setText("Atpakaļ");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jLabel23.setText("jLabel23");

        jLabel24.setText("jLabel24");

        jLabel25.setText("jLabel25");

        jLabel26.setText("jLabel26");

        jLabel27.setText("jLabel27");

        javax.swing.GroupLayout SlavasSarakstaLogsLayout = new javax.swing.GroupLayout(SlavasSarakstaLogs.getContentPane());
        SlavasSarakstaLogs.getContentPane().setLayout(SlavasSarakstaLogsLayout);
        SlavasSarakstaLogsLayout.setHorizontalGroup(
            SlavasSarakstaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SlavasSarakstaLogsLayout.createSequentialGroup()
                .addGroup(SlavasSarakstaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SlavasSarakstaLogsLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel16))
                    .addGroup(SlavasSarakstaLogsLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel15))
                    .addGroup(SlavasSarakstaLogsLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(SlavasSarakstaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SlavasSarakstaLogsLayout.createSequentialGroup()
                .addGap(0, 113, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        SlavasSarakstaLogsLayout.setVerticalGroup(
            SlavasSarakstaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SlavasSarakstaLogsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(36, 36, 36)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addGap(35, 35, 35)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        IzvelesLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                IzvelesLogsWindowClosed(evt);
            }
        });

        jLabel17.setText("Tests \"Nosaukums\"");

        jLabel18.setText("Mēģinājumu skaits:");

        jButton10.setText("Pildīt vēlreiz");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jButton11.setText("Skatīt rezultātus");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout IzvelesLogsLayout = new javax.swing.GroupLayout(IzvelesLogs.getContentPane());
        IzvelesLogs.getContentPane().setLayout(IzvelesLogsLayout);
        IzvelesLogsLayout.setHorizontalGroup(
            IzvelesLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IzvelesLogsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(IzvelesLogsLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(IzvelesLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11)
                    .addComponent(jLabel17))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        IzvelesLogsLayout.setVerticalGroup(
            IzvelesLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IzvelesLogsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(35, 35, 35)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        PirmaJautajumaLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                PirmaJautajumaLogsWindowClosed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("1. Jautājums:");

        jCheckBox1.setText("1.Atbilde");

        jCheckBox2.setText("2.Atbilde");

        jCheckBox3.setText("3.Atbilde");

        jButton5.setText("Iesniegt");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PirmaJautajumaLogsLayout = new javax.swing.GroupLayout(PirmaJautajumaLogs.getContentPane());
        PirmaJautajumaLogs.getContentPane().setLayout(PirmaJautajumaLogsLayout);
        PirmaJautajumaLogsLayout.setHorizontalGroup(
            PirmaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PirmaJautajumaLogsLayout.createSequentialGroup()
                .addGroup(PirmaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PirmaJautajumaLogsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(PirmaJautajumaLogsLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PirmaJautajumaLogsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PirmaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox3))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        PirmaJautajumaLogsLayout.setVerticalGroup(
            PirmaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PirmaJautajumaLogsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3)
                .addGap(28, 28, 28)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        OtraJautajumaLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                OtraJautajumaLogsWindowClosed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("2. Jautājums:");

        jCheckBox4.setText("1.Atbilde");

        jCheckBox5.setText("2.Atbilde");

        jCheckBox6.setText("3.Atbilde");

        jButton12.setText("Iesniegt");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout OtraJautajumaLogsLayout = new javax.swing.GroupLayout(OtraJautajumaLogs.getContentPane());
        OtraJautajumaLogs.getContentPane().setLayout(OtraJautajumaLogsLayout);
        OtraJautajumaLogsLayout.setHorizontalGroup(
            OtraJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OtraJautajumaLogsLayout.createSequentialGroup()
                .addGroup(OtraJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OtraJautajumaLogsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19))
                    .addGroup(OtraJautajumaLogsLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OtraJautajumaLogsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(OtraJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox6))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        OtraJautajumaLogsLayout.setVerticalGroup(
            OtraJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OtraJautajumaLogsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel19)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jCheckBox4)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox5)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox6)
                .addGap(28, 28, 28)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TresaJautajumaLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                TresaJautajumaLogsWindowClosed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("3. Jautājums:");

        jCheckBox7.setText("1.Atbilde");

        jCheckBox8.setText("2.Atbilde");

        jCheckBox9.setText("3.Atbilde");

        jButton13.setText("Iesniegt");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TresaJautajumaLogsLayout = new javax.swing.GroupLayout(TresaJautajumaLogs.getContentPane());
        TresaJautajumaLogs.getContentPane().setLayout(TresaJautajumaLogsLayout);
        TresaJautajumaLogsLayout.setHorizontalGroup(
            TresaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TresaJautajumaLogsLayout.createSequentialGroup()
                .addGroup(TresaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TresaJautajumaLogsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20))
                    .addGroup(TresaJautajumaLogsLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TresaJautajumaLogsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(TresaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox8)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox9))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        TresaJautajumaLogsLayout.setVerticalGroup(
            TresaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TresaJautajumaLogsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel20)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jCheckBox7)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox8)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox9)
                .addGap(28, 28, 28)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CeturtaJautajumaLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                CeturtaJautajumaLogsWindowClosed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("4. Jautājums:");

        jCheckBox10.setText("1.Atbilde");

        jCheckBox11.setText("2.Atbilde");

        jCheckBox12.setText("3.Atbilde");

        jButton14.setText("Iesniegt");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CeturtaJautajumaLogsLayout = new javax.swing.GroupLayout(CeturtaJautajumaLogs.getContentPane());
        CeturtaJautajumaLogs.getContentPane().setLayout(CeturtaJautajumaLogsLayout);
        CeturtaJautajumaLogsLayout.setHorizontalGroup(
            CeturtaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CeturtaJautajumaLogsLayout.createSequentialGroup()
                .addGroup(CeturtaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CeturtaJautajumaLogsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21))
                    .addGroup(CeturtaJautajumaLogsLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CeturtaJautajumaLogsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CeturtaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox11)
                            .addComponent(jCheckBox10)
                            .addComponent(jCheckBox12))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        CeturtaJautajumaLogsLayout.setVerticalGroup(
            CeturtaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CeturtaJautajumaLogsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel21)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jCheckBox10)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox11)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox12)
                .addGap(28, 28, 28)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PiektaJautajumaLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                PiektaJautajumaLogsWindowClosed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("5. Jautājums:");

        jCheckBox13.setText("1.Atbilde");

        jCheckBox14.setText("2.Atbilde");

        jCheckBox15.setText("3.Atbilde");

        jButton15.setText("Iesniegt");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PiektaJautajumaLogsLayout = new javax.swing.GroupLayout(PiektaJautajumaLogs.getContentPane());
        PiektaJautajumaLogs.getContentPane().setLayout(PiektaJautajumaLogsLayout);
        PiektaJautajumaLogsLayout.setHorizontalGroup(
            PiektaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PiektaJautajumaLogsLayout.createSequentialGroup()
                .addGroup(PiektaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PiektaJautajumaLogsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22))
                    .addGroup(PiektaJautajumaLogsLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PiektaJautajumaLogsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PiektaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox14)
                            .addComponent(jCheckBox13)
                            .addComponent(jCheckBox15))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        PiektaJautajumaLogsLayout.setVerticalGroup(
            PiektaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PiektaJautajumaLogsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel22)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jCheckBox13)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox14)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox15)
                .addGap(28, 28, 28)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainPage");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Lietotājvārds:");

        jLabel2.setText("Parole:");

        jButton1.setText("Ielogoties");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        RegistrationButton.setText("Reģistrēties");
        RegistrationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrationButtonMouseClicked(evt);
            }
        });
        RegistrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(RegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void TestStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TestStartActionPerformed

    private void RegistrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrationButtonActionPerformed

    private void RegistrationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrationButtonMouseClicked
        RegistracijasLogs.setBounds(0, 0, 400, 500);
        this.setVisible(false);
        RegistracijasLogs.setVisible(true);
    }//GEN-LAST:event_RegistrationButtonMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void RegistrationConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrationConfirmMouseClicked
        RegistracijasLogs.setVisible(false);
        this.setBounds(0, 0, 400, 350);
        this.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_RegistrationConfirmMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
         String username = jTextField1.getText();
    String password = new String(jPasswordField1.getPassword());

    try (Connection conn = getConnection()) {

        String sql = "SELECT * FROM users WHERE username = ? AND password = ?";
        PreparedStatement ps = conn.prepareStatement(sql);

        ps.setString(1, username);
        ps.setString(2, password);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ielogošanās veiksmīga!");

            TestaSakumsLogs.setBounds(0, 0, 400, 250);
            this.setVisible(false);
            TestaSakumsLogs.setVisible(true);

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Nepareizs lietotājvārds vai parole!");
        }

    } catch (SQLException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton1MouseClicked

    private void TestaSakumsLogsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_TestaSakumsLogsWindowClosed
        this.setVisible(true);
    }//GEN-LAST:event_TestaSakumsLogsWindowClosed

    private void TestStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TestStartMouseClicked
        TestaSakumsLogs.setVisible(false);
        PirmaJautajumaLogs.setBounds(0, 0, 400, 300);
        this.setVisible(false);
        PirmaJautajumaLogs.setVisible(true);
    }//GEN-LAST:event_TestStartMouseClicked

    private void RegistracijasLogsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_RegistracijasLogsWindowClosed
        this.setVisible(true);
    }//GEN-LAST:event_RegistracijasLogsWindowClosed

    private void RegistrationConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrationConfirmActionPerformed

    private void RegistracijasLogsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistracijasLogsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistracijasLogsMouseClicked

    private void OtraJautajumaLogsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_OtraJautajumaLogsWindowClosed
        this.setVisible(true);
    }//GEN-LAST:event_OtraJautajumaLogsWindowClosed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        OtraJautajumaLogs.setVisible(false);
        TresaJautajumaLogs.setBounds(0, 0, 400, 300);
        this.setVisible(false);
        TresaJautajumaLogs.setVisible(true);    }//GEN-LAST:event_jButton12MouseClicked

    private void PirmaJautajumaLogsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_PirmaJautajumaLogsWindowClosed
        this.setVisible(true);
    }//GEN-LAST:event_PirmaJautajumaLogsWindowClosed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        PirmaJautajumaLogs.setVisible(false);
        OtraJautajumaLogs.setBounds(0, 0, 400, 300);
        this.setVisible(false);
        OtraJautajumaLogs.setVisible(true);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        TresaJautajumaLogs.setVisible(false);
        CeturtaJautajumaLogs.setBounds(0, 0, 400, 300);
        this.setVisible(false);
        CeturtaJautajumaLogs.setVisible(true);
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        CeturtaJautajumaLogs.setVisible(false);
        PiektaJautajumaLogs.setBounds(0, 0, 400, 300);
        this.setVisible(false);
        PiektaJautajumaLogs.setVisible(true);
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        PiektaJautajumaLogs.setVisible(false);
        RezultatuLogs.setBounds(0, 0, 400, 300);
        this.setVisible(false);
        RezultatuLogs.setVisible(true);
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        RezultatuLogs.setVisible(false);
        SlavasSarakstaLogs.setBounds(0, 0, 400, 330);
        this.setVisible(false);
        SlavasSarakstaLogs.setVisible(true);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        SlavasSarakstaLogs.setVisible(false);
        RezultatuLogs.setBounds(0, 0, 400, 400);
        this.setVisible(false);
        RezultatuLogs.setVisible(true);
    }//GEN-LAST:event_jButton9MouseClicked

    private void RezultatuLogsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_RezultatuLogsWindowClosed
        this.setVisible(true);
    }//GEN-LAST:event_RezultatuLogsWindowClosed

    private void SlavasSarakstaLogsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_SlavasSarakstaLogsWindowClosed
        this.setVisible(true);
    }//GEN-LAST:event_SlavasSarakstaLogsWindowClosed

    private void IzvelesLogsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_IzvelesLogsWindowClosed
        this.setVisible(true);
    }//GEN-LAST:event_IzvelesLogsWindowClosed

    private void TresaJautajumaLogsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_TresaJautajumaLogsWindowClosed
        this.setVisible(true);
    }//GEN-LAST:event_TresaJautajumaLogsWindowClosed

    private void CeturtaJautajumaLogsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_CeturtaJautajumaLogsWindowClosed
        this.setVisible(true);
    }//GEN-LAST:event_CeturtaJautajumaLogsWindowClosed

    private void PiektaJautajumaLogsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_PiektaJautajumaLogsWindowClosed
        this.setVisible(true);
    }//GEN-LAST:event_PiektaJautajumaLogsWindowClosed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        SlavasSarakstaLogs.setVisible(false);
        IzvelesLogs.setBounds(0, 0, 400, 400);
        this.setVisible(false);
        IzvelesLogs.setVisible(true);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        IzvelesLogs.setVisible(false);
        PirmaJautajumaLogs.setBounds(0, 0, 400, 400);
        this.setVisible(false);
        PirmaJautajumaLogs.setVisible(true);
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        IzvelesLogs.setVisible(false);
        RezultatuLogs.setBounds(0, 0, 400, 400);
        this.setVisible(false);
        RezultatuLogs.setVisible(true);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PD1_GUI_Plehanovs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PD1_GUI_Plehanovs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PD1_GUI_Plehanovs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PD1_GUI_Plehanovs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PD1_GUI_Plehanovs().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CeturtaJautajumaLogs;
    private javax.swing.JDialog IzvelesLogs;
    private javax.swing.JDialog OtraJautajumaLogs;
    private javax.swing.JDialog PiektaJautajumaLogs;
    private javax.swing.JDialog PirmaJautajumaLogs;
    private javax.swing.JDialog RegistracijasLogs;
    private javax.swing.JButton RegistrationButton;
    private javax.swing.JButton RegistrationConfirm;
    private javax.swing.JDialog RezultatuLogs;
    private javax.swing.JDialog SlavasSarakstaLogs;
    private javax.swing.JButton TestStart;
    private javax.swing.JDialog TestaSakumsLogs;
    private javax.swing.JDialog TresaJautajumaLogs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
