/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pd1_test_plehanovs;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.event.WindowEvent;

/**
 * Galvenā GUI klase — pierakstīšanās un reģistrācijas forma. Pārvalda logu
 * navigāciju un DB operācijas.
 *
 * @author Maksims Pļehanovs
 */
public class PD1_GUI_Plehanovs extends javax.swing.JFrame {

    private static final String url = "jdbc:derby://localhost:1527/QuizDB";
    private static final String user = "dbuser";
    private static final String password = "dbuser";
    private int attemptCount = 0;
    /**
     * Izveido savienojumu ar datu bāzi, izmantojot hardkodētus parametrus.
     *
     * @return Connection objekts
     * @throws SQLException ja savienojums neizdodas
     */
    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(url, user, password);
    }

    /**
     * Creates new form PD1_GUI_Plehanovs
     */
    public PD1_GUI_Plehanovs() {
        initComponents();
    }

    /**
     * Reprezentē vienu testa jautājumu ar trim atbilžu variantiem.
     */
    public static class Question {

        public int id;
        public String questionText;
        public String[] options = new String[3];

        public Question(int id, String qText, String opt1, String opt2, String opt3) {
            this.id = id;
            this.questionText = qText;
            this.options[0] = opt1;
            this.options[1] = opt2;
            this.options[2] = opt3;
        }
    }

    /**
     * Iegūst jautājumu no datu bāzes pēc ID.
     *
     * @param questionId jautājuma ID
     * @return Question objekts vai null ja nav atrasts
     */
    public Question getQuestionById(int questionId) {
        try (Connection conn = PD1_GUI_Plehanovs.getConnection()) {
            String sql = "SELECT * FROM questions WHERE id = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, questionId);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                return new Question(
                        rs.getInt("id"),
                        rs.getString("question_text"),
                        rs.getString("option1"),
                        rs.getString("option2"),
                        rs.getString("option3")
                );
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TestaSakumsLogs = new javax.swing.JDialog();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        TestStart2 = new javax.swing.JButton();
        RezultatuLogs = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        SlavasSarakstaLogs = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        IzvelesLogs = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        PirmaJautajumaLogs = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();
        RegistracijasLogs = new javax.swing.JDialog();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        RegistrationConfirm1 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jPasswordField5 = new javax.swing.JPasswordField();
        lietotajvards_jTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        RegistrationButton = new javax.swing.JButton();
        parole_jPasswordField = new javax.swing.JPasswordField();

        TestaSakumsLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                TestaSakumsLogsWindowClosed(evt);
            }
        });

        jLabel31.setText("Tests \"Testa nosaukums\"");

        jLabel32.setText("Meģinājuma skaits: ");

        TestStart2.setText("Sākt testu");
        TestStart2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TestStartMouseClicked(evt);
            }
        });
        TestStart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TestaSakumsLogsLayout = new javax.swing.GroupLayout(TestaSakumsLogs.getContentPane());
        TestaSakumsLogs.getContentPane().setLayout(TestaSakumsLogsLayout);
        TestaSakumsLogsLayout.setHorizontalGroup(
            TestaSakumsLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestaSakumsLogsLayout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addGroup(TestaSakumsLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TestStart2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(TestaSakumsLogsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TestaSakumsLogsLayout.setVerticalGroup(
            TestaSakumsLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestaSakumsLogsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel31)
                .addGap(34, 34, 34)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(TestStart2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        RezultatuLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                RezultatuLogsWindowClosed(evt);
            }
        });

        jLabel11.setText("Rezultāti");

        jLabel12.setText("Lietotājs:");

        jLabel13.setText("Procenti:");

        jLabel14.setText("Atzīme:");

        jButton6.setText("Iesniegt");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Pildīt vēlreiz");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Paradīt Slavas sarakstu");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RezultatuLogsLayout = new javax.swing.GroupLayout(RezultatuLogs.getContentPane());
        RezultatuLogs.getContentPane().setLayout(RezultatuLogsLayout);
        RezultatuLogsLayout.setHorizontalGroup(
            RezultatuLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RezultatuLogsLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(RezultatuLogsLayout.createSequentialGroup()
                .addGroup(RezultatuLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RezultatuLogsLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(RezultatuLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(87, 87, 87)
                        .addComponent(jLabel14))
                    .addGroup(RezultatuLogsLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel11))
                    .addGroup(RezultatuLogsLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RezultatuLogsLayout.setVerticalGroup(
            RezultatuLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RezultatuLogsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(31, 31, 31)
                .addComponent(jLabel12)
                .addGap(35, 35, 35)
                .addGroup(RezultatuLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(RezultatuLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        SlavasSarakstaLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                SlavasSarakstaLogsWindowClosed(evt);
            }
        });

        jLabel15.setText("Slavas saraksts");

        jLabel16.setText("Rezultāti");

        jButton9.setText("Atpakaļ");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jLabel23.setText("jLabel23");

        jLabel24.setText("jLabel24");

        jLabel25.setText("jLabel25");

        jLabel26.setText("jLabel26");

        jLabel27.setText("jLabel27");

        javax.swing.GroupLayout SlavasSarakstaLogsLayout = new javax.swing.GroupLayout(SlavasSarakstaLogs.getContentPane());
        SlavasSarakstaLogs.getContentPane().setLayout(SlavasSarakstaLogsLayout);
        SlavasSarakstaLogsLayout.setHorizontalGroup(
            SlavasSarakstaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SlavasSarakstaLogsLayout.createSequentialGroup()
                .addGroup(SlavasSarakstaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SlavasSarakstaLogsLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel16))
                    .addGroup(SlavasSarakstaLogsLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel15))
                    .addGroup(SlavasSarakstaLogsLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(SlavasSarakstaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SlavasSarakstaLogsLayout.createSequentialGroup()
                .addGap(0, 113, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        SlavasSarakstaLogsLayout.setVerticalGroup(
            SlavasSarakstaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SlavasSarakstaLogsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(36, 36, 36)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addGap(35, 35, 35)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        IzvelesLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                IzvelesLogsWindowClosed(evt);
            }
        });

        jLabel17.setText("Tests \"Nosaukums\"");

        jLabel18.setText("Mēģinājumu skaits:");

        jButton10.setText("Pildīt vēlreiz");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Skatīt rezultātus");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IzvelesLogsLayout = new javax.swing.GroupLayout(IzvelesLogs.getContentPane());
        IzvelesLogs.getContentPane().setLayout(IzvelesLogsLayout);
        IzvelesLogsLayout.setHorizontalGroup(
            IzvelesLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IzvelesLogsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(IzvelesLogsLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(IzvelesLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11)
                    .addComponent(jLabel17))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        IzvelesLogsLayout.setVerticalGroup(
            IzvelesLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IzvelesLogsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(35, 35, 35)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        PirmaJautajumaLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                PirmaJautajumaLogsWindowClosed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("1. Jautājums:");

        jCheckBox1.setText("1.Atbilde");

        jCheckBox2.setText("2.Atbilde");

        jCheckBox3.setText("3.Atbilde");

        jButton5.setText("Iesniegt");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PirmaJautajumaLogsLayout = new javax.swing.GroupLayout(PirmaJautajumaLogs.getContentPane());
        PirmaJautajumaLogs.getContentPane().setLayout(PirmaJautajumaLogsLayout);
        PirmaJautajumaLogsLayout.setHorizontalGroup(
            PirmaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PirmaJautajumaLogsLayout.createSequentialGroup()
                .addGroup(PirmaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PirmaJautajumaLogsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(PirmaJautajumaLogsLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PirmaJautajumaLogsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PirmaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox3))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        PirmaJautajumaLogsLayout.setVerticalGroup(
            PirmaJautajumaLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PirmaJautajumaLogsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3)
                .addGap(28, 28, 28)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        RegistracijasLogs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistracijasLogsMouseClicked(evt);
            }
        });
        RegistracijasLogs.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                RegistracijasLogsWindowClosed(evt);
            }
        });

        jLabel33.setText("Vārds:");

        jLabel34.setText("Uzvārds:");

        jLabel35.setText("Lietotājvārds:");

        jLabel36.setText("Parole:");

        jLabel37.setText("Parole(atkārtoti):");

        RegistrationConfirm1.setText("Reģistrēties");
        RegistrationConfirm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrationConfirm1MouseClicked(evt);
            }
        });
        RegistrationConfirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationConfirm1ActionPerformed(evt);
            }
        });

        jPasswordField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegistracijasLogsLayout = new javax.swing.GroupLayout(RegistracijasLogs.getContentPane());
        RegistracijasLogs.getContentPane().setLayout(RegistracijasLogsLayout);
        RegistracijasLogsLayout.setHorizontalGroup(
            RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistracijasLogsLayout.createSequentialGroup()
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistracijasLogsLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37))
                        .addGap(18, 18, 18)
                        .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RegistracijasLogsLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(RegistrationConfirm1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegistracijasLogsLayout.setVerticalGroup(
            RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistracijasLogsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(RegistracijasLogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jPasswordField5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RegistrationConfirm1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainPage");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lietotajvards_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lietotajvards_jTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Lietotājvārds:");

        jLabel2.setText("Parole:");

        jButton1.setText("Ielogoties");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        RegistrationButton.setText("Reģistrēties");
        RegistrationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrationButtonMouseClicked(evt);
            }
        });
        RegistrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(RegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lietotajvards_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(parole_jPasswordField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lietotajvards_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(parole_jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lietotajvards_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lietotajvards_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lietotajvards_jTextFieldActionPerformed

    private void RegistrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrationButtonActionPerformed

    private void RegistrationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrationButtonMouseClicked
        RegistracijasLogs.setBounds(0, 0, 400, 500);
        this.setVisible(false);
        RegistracijasLogs.setVisible(true);
    }//GEN-LAST:event_RegistrationButtonMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * Apstrādā pieteikšanās pogas klikšķi. Pārbauda lietotājvārdu un paroli
     * datu bāzē.
     */

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
String login = lietotajvards_jTextField.getText();
String password = new String(parole_jPasswordField.getPassword());
    Test test = new Test();
    if (test.login(login, password)) {
        JOptionPane.showMessageDialog(this, "Veiksmīga ielogošanā!");
        TestaSakumsLogs.setBounds(0, 0, 400, 400);
        TestaSakumsLogs.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Nepareizs lietotājvārds vai parole!");
    }
    }//GEN-LAST:event_jButton1MouseClicked

    private void PirmaJautajumaLogsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_PirmaJautajumaLogsWindowClosed
        this.setVisible(true);
    }//GEN-LAST:event_PirmaJautajumaLogsWindowClosed
private Test currentTest = new Test();
private Students currentStudent = new Students();
private int currentQuestionIndex = 0;
    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
/**
     * Apstrādā atbildes iesniegšanu.
     * Pārbauda izvēlēto atbildi, palielina jautājumu indeksu
     * un pāriet uz nākamo jautājumu vai rāda rezultātus.
     */
    String selectedAnswer = "";
    if (jCheckBox1.isSelected()) selectedAnswer = jCheckBox1.getText();
    else if (jCheckBox2.isSelected()) selectedAnswer = jCheckBox2.getText();
    else if (jCheckBox3.isSelected()) selectedAnswer = jCheckBox3.getText();


    Jautajumi question = currentTest.getQuestion(currentQuestionIndex);
    currentStudent.getAnswers(question, selectedAnswer);

    currentQuestionIndex++;

    if (currentQuestionIndex < currentTest.getQuestionCount()) {

        loadQuestionToDialog(currentQuestionIndex);
    } else {

        PirmaJautajumaLogs.setVisible(false);
        showResult();
    }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        RezultatuLogs.setVisible(false);
        SlavasSarakstaLogs.setBounds(0, 0, 400, 330);
        this.setVisible(false);
        SlavasSarakstaLogs.setVisible(true);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        SlavasSarakstaLogs.setVisible(false);
        RezultatuLogs.setBounds(0, 0, 400, 400);
        this.setVisible(false);
        RezultatuLogs.setVisible(true);
    }//GEN-LAST:event_jButton9MouseClicked

    private void RezultatuLogsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_RezultatuLogsWindowClosed
       IzvelesLogs.setBounds(0, 0, 400, 400);
    IzvelesLogs.setVisible(true);
    }//GEN-LAST:event_RezultatuLogsWindowClosed

    private void SlavasSarakstaLogsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_SlavasSarakstaLogsWindowClosed
        this.setVisible(true);
    }//GEN-LAST:event_SlavasSarakstaLogsWindowClosed

    private void IzvelesLogsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_IzvelesLogsWindowClosed
        this.setVisible(true);
    }//GEN-LAST:event_IzvelesLogsWindowClosed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
    RezultatuLogs.setVisible(false);
    IzvelesLogs.setBounds(0, 0, 400, 400);
    IzvelesLogs.setVisible(true);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
if (attemptCount >= 3) {
        JOptionPane.showMessageDialog(null, "Jūs esat izmantojis visus 3 mēģinājumus!");
        return;
    }

    attemptCount++;
    currentQuestionIndex = 0;
    currentStudent = new Students();
    loadQuestionToDialog(currentQuestionIndex);

    IzvelesLogs.setVisible(false);
    PirmaJautajumaLogs.setBounds(0, 0, 400, 300);
    PirmaJautajumaLogs.setVisible(true);
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        IzvelesLogs.setVisible(false);
        RezultatuLogs.setBounds(0, 0, 400, 400);
        this.setVisible(false);
        RezultatuLogs.setVisible(true);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        RezultatuLogs.setVisible(false);
        PirmaJautajumaLogs.setBounds(0, 0, 400, 300);
        this.setVisible(false);
        PirmaJautajumaLogs.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        IzvelesLogs.setVisible(false);
        PirmaJautajumaLogs.setBounds(0, 0, 400, 300);
        this.setVisible(false);
        PirmaJautajumaLogs.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void TestaSakumsLogsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_TestaSakumsLogsWindowClosed
        this.setVisible(true);
    }//GEN-LAST:event_TestaSakumsLogsWindowClosed

    private void TestStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TestStartActionPerformed

    private void TestStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TestStartMouseClicked
    currentTest.loadQuestionsFromDB(1);

    if (currentTest.getQuestionCount() == 0) {
        JOptionPane.showMessageDialog(null, "Nav jautājumu datubāzē!");
        return;
    }

    attemptCount = 1; 
    currentQuestionIndex = 0;
    currentStudent = new Students();
    loadQuestionToDialog(currentQuestionIndex);

    TestaSakumsLogs.setVisible(false);
    this.setVisible(false);
    PirmaJautajumaLogs.setBounds(0, 0, 400, 300);
    PirmaJautajumaLogs.setVisible(true);
    }//GEN-LAST:event_TestStartMouseClicked
private void loadQuestionToDialog(int index) {
    Jautajumi q = currentTest.getQuestion(index);
    java.util.List<String> options = q.getAnswerOptions();

    jLabel10.setText((index + 1) + ". " + q.getText());
    jCheckBox1.setText(options.size() > 0 ? options.get(0) : "");
    jCheckBox2.setText(options.size() > 1 ? options.get(1) : "");
    jCheckBox3.setText(options.size() > 2 ? options.get(2) : "");

   
    jCheckBox1.setSelected(false);
    jCheckBox2.setSelected(false);
    jCheckBox3.setSelected(false);
}

private void showResult() {
   int percent = currentStudent.getPercent();
    int grade   = currentStudent.getGrade();
    int right   = currentStudent.getRightAnswers();
    int total   = currentStudent.getQuestionsCount();

    jLabel12.setText("Lietotājs: ");
    jLabel13.setText("Procenti: " + percent + "%");
    jLabel14.setText("Atzīme: " + grade);

  
    int remaining = 3 - attemptCount;
    jLabel18.setText("Mēģinājumu skaits: " + remaining + " atlikuši");


    jButton7.setVisible(remaining > 0);

    PirmaJautajumaLogs.setVisible(false);
    RezultatuLogs.setBounds(0, 0, 400, 400);
    RezultatuLogs.setVisible(true);
}
    /**
     * Apstrādā reģistrācijas pogas klikšķi reģistrācijas formā. Pārbauda
     * ievades datus, lietotājvārda unikālumu un saglabā jauno lietotāju DB.
     */

    private void RegistrationConfirm1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrationConfirm1MouseClicked
        String vards = jTextField6.getText().trim();
        String uzvards = jTextField7.getText().trim();
        String lietotajvards = jTextField8.getText().trim();
        String parole = new String(jPasswordField4.getPassword()).trim();
        String paroleAtk = new String(jPasswordField5.getPassword()).trim();

        // Pārbaude vai visi lauki ir aizpildīti
        if (vards.isEmpty() || uzvards.isEmpty() || lietotajvards.isEmpty() || parole.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lūdzu aizpildiet visus laukus!");
            return;
        }

        // Pārbaude vai paroles sakrīt
        if (!parole.equals(paroleAtk)) {
            JOptionPane.showMessageDialog(this, "Paroles nesakrīt!");
            return;
        }

        try (Connection conn = DBConnection.getConnection()) {
            // Pārbaude vai lietotājvārds jau eksistē
            String checkSql = "SELECT COUNT(*) FROM APP.LIETOTAJI WHERE LIETOTAJVARDS = ?";
            PreparedStatement checkStmt = conn.prepareStatement(checkSql);
            checkStmt.setString(1, lietotajvards);
            ResultSet rs = checkStmt.executeQuery();
            rs.next();
            if (rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(this, "Lietotājvārds jau eksistē!");
                return;
            }

            // Ieraksta jauno lietotāju
            String maxIdSql = "SELECT COALESCE(MAX(ID), 0) + 1 FROM APP.LIETOTAJI";
            PreparedStatement maxStmt = conn.prepareStatement(maxIdSql);
            ResultSet maxRs = maxStmt.executeQuery();
            maxRs.next();
            int newId = maxRs.getInt(1);

            String sql = "INSERT INTO APP.LIETOTAJI (ID, VARDS, UZVARDS, LIETOTAJVARDS, PAROLE) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1, newId);
            stmt.setString(2, vards);
            stmt.setString(3, uzvards);
            stmt.setString(4, lietotajvards);
            stmt.setString(5, parole);
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Reģistrācija veiksmīga!");
            RegistracijasLogs.setVisible(false);
            this.setVisible(true);

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Kļūda reģistrācijā: " + e.getMessage());
        }

    }//GEN-LAST:event_RegistrationConfirm1MouseClicked

    private void RegistrationConfirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationConfirm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrationConfirm1ActionPerformed

    private void jPasswordField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField4ActionPerformed

    private void RegistracijasLogsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistracijasLogsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistracijasLogsMouseClicked

    private void RegistracijasLogsWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_RegistracijasLogsWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistracijasLogsWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PD1_GUI_Plehanovs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PD1_GUI_Plehanovs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PD1_GUI_Plehanovs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PD1_GUI_Plehanovs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PD1_GUI_Plehanovs().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog IzvelesLogs;
    private javax.swing.JDialog PirmaJautajumaLogs;
    private javax.swing.JDialog RegistracijasLogs;
    private javax.swing.JButton RegistrationButton;
    private javax.swing.JButton RegistrationConfirm1;
    private javax.swing.JDialog RezultatuLogs;
    private javax.swing.JDialog SlavasSarakstaLogs;
    private javax.swing.JButton TestStart2;
    private javax.swing.JDialog TestaSakumsLogs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField lietotajvards_jTextField;
    private javax.swing.JPasswordField parole_jPasswordField;
    // End of variables declaration//GEN-END:variables
}
